{{- if .Values.opentelemetry.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Values.opentelemetry.config.name }}
  namespace: {{ .Release.Namespace }}
data: 
  {{ .Values.opentelemetry.config.name }}: {{ .Values.opentelemetry.config.data }}
{{- end }}
